### ISSUE TITLE
Foot and Mouth disease study

### ISSUE THREAD

**Issue by bengalspice** [dougE83/intro-data-capstone-biodiversity#7]
While you did explain the importance of the sample size calculation, you didn't actually show what the calculation was, the results, and how long the study needs to be run. All of this information that you were asked to code for is missing from the slides.

**Comment by dougE83** [comment]
I wasn't sure about if we were to pull the values from the code and it wouldn't of mattered since I had the wrong file uploaded as well that was blank.  I am updating everything and I will be replying to your email here shortly.

**Comment by bengalspice** [comment]
Thank you for making this revision
